// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package echo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	GetData(ctx context.Context, opts ...grpc.CallOption) (Echo_GetDataClient, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) GetData(ctx context.Context, opts ...grpc.CallOption) (Echo_GetDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], "/echo.Echo/GetData", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoGetDataClient{stream}
	return x, nil
}

type Echo_GetDataClient interface {
	Send(*GetDataRequest) error
	Recv() (*Data, error)
	grpc.ClientStream
}

type echoGetDataClient struct {
	grpc.ClientStream
}

func (x *echoGetDataClient) Send(m *GetDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoGetDataClient) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility
type EchoServer interface {
	GetData(Echo_GetDataServer) error
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (UnimplementedEchoServer) GetData(Echo_GetDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_GetData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).GetData(&echoGetDataServer{stream})
}

type Echo_GetDataServer interface {
	Send(*Data) error
	Recv() (*GetDataRequest, error)
	grpc.ServerStream
}

type echoGetDataServer struct {
	grpc.ServerStream
}

func (x *echoGetDataServer) Send(m *Data) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoGetDataServer) Recv() (*GetDataRequest, error) {
	m := new(GetDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetData",
			Handler:       _Echo_GetData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "echo/service.proto",
}
